-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), 
	COUNT(distinct sale.USER_ID), 
	ROUND((COUNT(distinct sale.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021-%'), 1) AS PURCHASED_RATIO
FROM USER_INFO AS user
LEFT JOIN ONLINE_SALE AS sale ON user.USER_ID = sale.USER_ID
WHERE JOINED LIKE '2021-%' && sale.USER_ID IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE);