-- 코드를 입력하세요
SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_OUTS AS o
LEFT JOIN ANIMAL_INS AS i ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%' 
    && (SEX_UPON_OUTCOME LIKE 'Spayed%' || SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY o.ANIMAL_ID
