-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS a
WHERE (SELECT COUNT(*) 
       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
       WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
            && b.CAR_ID = a.CAR_ID 
       GROUP BY CAR_ID) >= 5
       && START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# WHERE a.CAR_ID IN (SELECT b.CAR_ID
#        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
#        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
#        GROUP BY CAR_ID
#         HAVING COUNT(*) >= 5)
#     && START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(*) != 0
ORDER BY MONTH ASC, CAR_ID DESC