-- 코드를 입력하세요
WITH RECURSIVE TIMETABLE AS (
    SELECT 0 AS HOURS, 0 AS NUM
    UNION ALL 
    SELECT HOURS + 1, NUM 
    FROM TIMETABLE
    WHERE HOURS < 23
)

SELECT HOURS AS HOUR, 
    IFNULL((SELECT COUNT(*) 
     FROM ANIMAL_OUTS AS o
     WHERE DATE_FORMAT(DATETIME, '%k') = HOURS
     GROUP BY HOUR(DATETIME)) + NUM, 0) AS COUNT
FROM TIMETABLE 
# JOIN TIMETABLE AS time
# WHERE DATE_FORMAT(DATETIME, '%k') = time.HOURS
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR;