-- 코드를 입력하세요
# SELECT f.FLAVOR
# FROM FIRST_HALF AS f
# JOIN JULY AS j ON f.SHIPMENT_ID = j.SHIPMENT_ID
# WHERE (SELECT SUM(TOTAL_ORDER) FROM FIRST_HALF GROUP BY FLAVOR) 
#     + (SELECT SUM(TOTAL_ORDER) FROM JULY GROUP BY FLAVOR)
# ;

# SELECT ((SELECT SUM(TOTAL_ORDER) FROM FIRST_HALF) 
#     + (SELECT SUM(TOTAL_ORDER) FROM JULY) AS FLAVOR
# FROM FIRST_HALF AS f
# JOIN JULY AS j ON f.SHIPMENT_ID = j.SHIPMENT_ID
# GROUP BY FLAVOR
        
        SELECT
    A.FLAVOR
FROM
    FIRST_HALF A
LEFT JOIN JULY B ON
    A.FLAVOR = B.FLAVOR
GROUP BY
    A.FLAVOR
ORDER BY
    SUM(A.TOTAL_ORDER+B.TOTAL_ORDER) DESC
    LIMIT 3