-- 코드를 입력하세요
# SELECT MEMBER_NAME, REVIEW_TEXT, SUBSTRING(REVIEW_DATE, 1, 10)
# FROM MEMBER_PROFILE AS m
# JOIN REST_REVIEW AS r ON m.MEMBER_ID = r.MEMBER_ID
# WHERE r.MEMBER_ID IN (
#     SELECT c.MEMBER_ID
#     FROM REST_REVIEW AS c
#     GROUP BY c.MEMBER_ID
#     HAVING COUNT(*) = (
#         SELECT COUNT(*)
#         FROM REST_REVIEW AS d
#         GROUP BY d.MEMBER_ID
#         ORDER BY COUNT(*) DESC
#         LIMIT 1
#     ))
# ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;

SELECT MEMBER_NAME, REVIEW_TEXT, SUBSTRING(REVIEW_DATE, 1, 10)
FROM MEMBER_PROFILE AS m
JOIN REST_REVIEW AS r ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;