-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS b
JOIN BOOK_SALES AS s ON b.BOOK_ID = s.BOOK_ID
WHERE  SUBSTRING(SALES_DATE, 1, 7) = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;