-- 코드를 입력하세요
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM BOOK AS b, AUTHOR AS a, BOOK_SALES AS s
WHERE SUBSTRING(s.SALES_DATE, 1, 7) = '2022-01'
    AND s.BOOK_ID = b.BOOK_ID
    AND b.AUTHOR_ID = a.AUTHOR_ID
GROUP BY a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;