-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, (p.PRICE * SUM(o.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS p
JOIN FOOD_ORDER AS o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 && MONTH(PRODUCE_DATE) = 5
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;
