-- 코드를 입력하세요
SELECT APNT_NO,
    (SELECT PT_NAME FROM PATIENT AS p WHERE p.PT_NO = a.PT_NO) AS PT_NAME,
    a.PT_NO AS PT_NO,
    a.MCDP_CD AS MCDP_CD,
    (SELECT DR_NAME FROM DOCTOR AS d WHERE d.DR_ID = a.MDDR_ID) AS DR_NAME,
    APNT_YMD
FROM APPOINTMENT AS a
WHERE APNT_YMD LIKE '2022-04-13%'
    && APNT_CNCL_YN = 'N'
    && MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;

# SELECT * FROM APPOINTMENT;