-- 코드를 입력하세요
# SELECT info.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,
#     (SELECT ROUND(AVG(REVIEW_SCORE), 2) 
#     FROM REST_REVIEW AS re 
#     WHERE re.REST_ID = info.REST_ID) AS SCORE
# FROM REST_INFO AS info
# WHERE ADDRESS LIKE '서울%'
#     && (SELECT ROUND(AVG(REVIEW_SCORE), 2) 
#         FROM REST_REVIEW AS re 
#         WHERE re.REST_ID = info.REST_ID) IS NOT NULL
# ORDER BY SCORE DESC, FAVORITES DESC;

SELECT info.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS info
JOIN REST_REVIEW AS re ON info.REST_ID = re.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY info.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;